services:
  mongodb:
    image: mongo:7.0.10-rc0-jammy
    container_name: mongodb
    ports:
      - "10001:27017"
    volumes:
      - chatting_server_mongodb_data:/data/db
    networks:
      - chatting_server

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "10002:6379"
    networks:
      - chatting_server

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - chatting_server
  
  socket:
    container_name: socket
    build:
      context: .
      dockerfile: apps/socket/dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
    networks:
      - chatting_server
  
  file:
    container_name: file
    build:
      context: .
      dockerfile: apps/file/dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - redis
    networks:
      - chatting_server
  
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: apps/worker/dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - redis
    networks:
      - chatting_server

volumes:
  chatting_server_mongodb_data:

networks:
  chatting_server: